image: node:20

variables:
    npm_config_cache: '$CI_PROJECT_DIR/.npm'

stages:
    - build

cache:
    key:
        files:
            - package-lock.json
    paths:
        - .npm/
    policy: pull

build-and-test:
    stage: build
    timeout: 5m
    variables:
        CYPRESS_INSTALL_BINARY: 0
    script:
        - npm ci --cache .npm --prefer-offline
        # Run prebuild steps and build ui packages so imported generated files are there
        - npm run prebuild -w packages/sdk
        - npm run build -w packages/ui

        - npm run lint:ci -w packages/sdk
        - npm run type-check -w packages/sdk
        - npm run test:unit -w packages/sdk
        - npm run translations:extract -w packages/sdk
        - npm run translations:compile -w packages/sdk
        - npm run translations:check -w packages/sdk
        - npm run build -w packages/sdk
